### PR TITLE
wrapper rewritten, patches removed, make test, libhext and boost updated

### PR DESCRIPTION
**Pull request by thomastrapp**
I finally had time to look at hext-emscripten.

And I've made some changes:
* I have rewritten the wrapper. It now behaves almost exactly like the Hext nodejs module (https://github.com/brandonrobertz/hext-emscripten/commit/ec4d046c22a587e3e5e5b90623e4249dc043e5a5).
* I threw out the old wrapper. I don't know if this works for you :) Maybe we can have two build targets, 'new' and 'old wrapper'.

Ideally, I'd like to see hext-emscripten be included in the html-extract organization. Let me know if you are willing to join.

Either way, thanks for setting up this project. I wouldn't have known where to start without a working base to build upon.

### CODE REVIEW

**Comment by brandonrobertz** [comment]
Hey! Thanks for your work on this. I'm willing to move this into the hext org namespace. Just let me know what I need to do to make this happen.

I like the direction of this, but when I was trying to do the build it fails. I checked against the master branch on my repo and it succeeds, so it doesn't look like an environment issue common to both branches. I'm not sure what your environment looks like, but basically all the deps build and then building libhext fails.

```
$ make
if ! which em++ 2> /dev/null || \
        ! which emar 2> /dev/null  || \
        ! which emmake 2> /dev/null || \
        ! which emcmake 2> /dev/null; then \
        echo "Emscripten not on PATH! Quitting."; \
        exit 1; \
fi
/home/brando/src/emsdk/emscripten/1.38.24/em++
/home/brando/src/emsdk/emscripten/1.38.24/emar
/home/brando/src/emsdk/emscripten/1.38.24/emmake
/home/brando/src/emsdk/emscripten/1.38.24/emcmake
mkdir -p build
mkdir -p build-dep
make -f Makefile.boost
make[1]: Entering directory '/home/brando/src/hext-emscripten-tomastrapp'
make[1]: Nothing to be done for 'boost'.
make[1]: Leaving directory '/home/brando/src/hext-emscripten-tomastrapp'
make -f Makefile.gumbo
make[1]: Entering directory '/home/brando/src/hext-emscripten-tomastrapp'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/brando/src/hext-emscripten-tomastrapp'
make -f Makefile.libhext
make[1]: Entering directory '/home/brando/src/hext-emscripten-tomastrapp'
cd build/hext-0.8.0/libhext/build && \
emcmake cmake \
        -DGumbo_LIBRARY=/home/brando/src/hext-emscripten-tomastrapp/build-dep/lib/libgumbo.a \
        -DGumbo_INCLUDE_DIR=/home/brando/src/hext-emscripten-tomastrapp/build-dep/include \
        -DBoost_INCLUDE_DIR=/home/brando/src/hext-emscripten-tomastrapp/build-dep/include \
        -DBoost_LIBRARY_DIR=/home/brando/src/hext-emscripten-tomastrapp/build-dep/lib \
        -DCMAKE_INSTALL_PREFIX=/home/brando/src/hext-emscripten-tomastrapp/build-dep \
        .. && \
emmake make install VERBOSE=1
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:32 (find_package)


-- Boost version: 1.70.0
-- Found the following Boost libraries:
--   regex
-- Configuring done
CMake Error at CMakeLists.txt:37 (add_library):
  Target "hext" links to target "Boost::regex" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:37 (add_library):
  Target "hext" links to target "Boost::regex" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/build
shared:ERROR: Configure step failed with non-zero return code: 1.  Command line: cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/brando/src/emsdk/node/8.9.1_64bit/bin/node" -DGumbo_LIBRARY=/home/brando/src/hext-emscripten-tomastrapp/build-dep/lib/libgumbo.a -DGumbo_INCLUDE_DIR=/home/brando/src/hext-emscripten-tomastrapp/build-dep/include -DBoost_INCLUDE_DIR=/home/brando/src/hext-emscripten-tomastrapp/build-dep/include -DBoost_LIBRARY_DIR=/home/brando/src/hext-emscripten-tomastrapp/build-dep/lib -DCMAKE_INSTALL_PREFIX=/home/brando/src/hext-emscripten-tomastrapp/build-dep .. -DCMAKE_TOOLCHAIN_FILE=/home/brando/src/emsdk/emscripten/1.38.24/cmake/Modules/Platform/Emscripten.cmake at /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/build
Makefile.libhext:18: recipe for target 'build-dep/lib/libhext.a' failed
make[1]: *** [build-dep/lib/libhext.a] Error 1
make[1]: Leaving directory '/home/brando/src/hext-emscripten-tomastrapp'
Makefile:15: recipe for target 'dependencies' failed
make: *** [dependencies] Error 2
```

And just so you can see my deps have been compiled:
```
build-dep/include:
boost  gumbo.h  tag_enum.h

build-dep/lib:
cmake      libboost_regex.bc  libboost_regex.so.1     libboost_regex.so.1.70.0  libgumbo.la
pkgconfig  libboost_regex.so  libboost_regex.so.1.70  libgumbo.a
```

My hunch is it's a result of the patches I had only working with that specific hext/boost version combination. I'm curious what your thoughts are. When I was first doing this cross-compilation, I had this same kind of problem when using cmake w/ emscripten. That's what led me to patch the CMakeLists.txt to pull in the emscripten compiled deps explicitly.

**Comment by thomastrapp** [comment]
The last commit should fix the issue.

> I'm willing to move this into the hext org namespace

Great! I've sent an invite.
After accepting, you should be able to transfer the repository the html-extract organization.
https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

Also we should add a license. Is Apache 2.0 okay for you?

**Comment by brandonrobertz** [comment]
Sorry about the long response cycle, I've been really busy with contracts. I get a different error with the latest master:

```
[Note: truncated to failing part ...]
[  2%] Building CXX object CMakeFiles/hext.dir/src/AppendPipe.cpp.o
/home/brando/src/emsdk/emscripten/1.38.24/em++  -DBOOST_ALL_NO_LIB @CMakeFiles/hext.dir/includes_CXX.rsp -DNDEBUG -O2 -fvisibility=hidden   -Weverything -Wno-c++98-compat -Wno-documentation -Wno-documentation-html -Wno-documentation-unknown-command -Wno-exit-time-destructors -Wno-global-constructors -Wno-padded -Wno-switch-enum -Wno-weak-vtables -o CMakeFiles/hext.dir/src/AppendPipe.cpp.o -c /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/src/AppendPipe.cpp
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/src/AppendPipe.cpp:15:
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/AppendPipe.h:21:
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/Cloneable.h:48:9: error:
      too many arguments provided to function-like macro invocation
        "template argument <Base> is not a base of "
        ^
/home/brando/src/emsdk/emscripten/1.38.24/system/include/libcxx/__config:805:12: note: macro
      'static_assert' defined here
#   define static_assert(__b, __m) _Static_assert(__b, __m)
           ^
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/src/AppendPipe.cpp:15:
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/AppendPipe.h:21:
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/Cloneable.h:47:5: error:
      use of undeclared identifier 'static_assert'
    static_assert(std::is_base_of<Base, Derived>::value,
    ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/Cloneable.h:50:5: warning:
      _Static_assert is a C11-specific feature [-Wc11-extensions]
    static_assert(std::is_copy_constructible<Derived>::value,
    ^
/home/brando/src/emsdk/emscripten/1.38.24/system/include/libcxx/__config:805:36: note: expanded from macro
      'static_assert'
#   define static_assert(__b, __m) _Static_assert(__b, __m)
                                   ^
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/src/AppendPipe.cpp:15:
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/AppendPipe.h:21:
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/Cloneable.h:54:17: error:
      no member named 'make_unique' in namespace 'std'
    return std::make_unique<Derived>(static_cast<const Derived&>(*this));
           ~~~~~^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/Cloneable.h:54:29: error:
      'Derived' does not refer to a value
    return std::make_unique<Derived>(static_cast<const Derived&>(*this));
                            ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/Cloneable.h:35:19: note:
      declared here
template<typename Derived, typename Base>
                  ^
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/src/AppendPipe.cpp:15:
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/AppendPipe.h:22:
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:43:16: warning:
      'noexcept' is a keyword in C++11 [-Wc++11-compat]
  StringPipe() noexcept;
               ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:43:15: error:
      expected ';' at end of declaration list
  StringPipe() noexcept;
              ^
              ;
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:45:24: warning:
      rvalue references are a C++11 extension [-Wc++11-extensions]
  StringPipe(StringPipe&&) noexcept = default;
                       ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:45:27: error:
      expected ';' at end of declaration list
  StringPipe(StringPipe&&) noexcept = default;
                          ^
                          ;
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:47:35: warning:
      rvalue references are a C++11 extension [-Wc++11-extensions]
  StringPipe& operator=(StringPipe&&) noexcept = default;
                                  ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:47:38: error:
      expected ';' at end of declaration list
  StringPipe& operator=(StringPipe&&) noexcept = default;
                                     ^
                                     ;
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:48:24: error:
      expected ';' at end of declaration list
  virtual ~StringPipe() noexcept = default;
                       ^
                       ;
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:66:48: error:
      expected ';' at end of declaration list
  void append(std::unique_ptr<StringPipe> pipe) noexcept;
                                               ^
                                               ;
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:69:45: warning:
      variadic templates are a C++11 extension [-Wc++11-extensions]
  template<typename StringPipeType, typename... Args>
                                            ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:70:20: warning:
      rvalue references are a C++11 extension [-Wc++11-extensions]
  void emplace(Args&&... arg)
                   ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:72:23: error:
      no member named 'make_unique' in namespace 'std'
    this->append(std::make_unique<StringPipeType>(std::forward<Args>(arg)...));
                 ~~~~~^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:72:35: error:
      'StringPipeType' does not refer to a value
    this->append(std::make_unique<StringPipeType>(std::forward<Args>(arg)...));
                                  ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:69:21: note:
      declared here
  template<typename StringPipeType, typename... Args>
                    ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:72:74: error:
      expected ')'
    this->append(std::make_unique<StringPipeType>(std::forward<Args>(arg)...));
                                                                         ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/StringPipe.h:72:50: note:
      to match this '('
    this->append(std::make_unique<StringPipeType>(std::forward<Args>(arg)...));
                                                 ^
In file included from /home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/src/AppendPipe.cpp:15:
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/AppendPipe.h:32:30: warning:
      'final' keyword is a C++11 extension [-Wc++11-extensions]
class HEXT_PUBLIC AppendPipe final
                             ^
/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/include/hext/AppendPipe.h:42:48: warning:
      'override' keyword is a C++11 extension [-Wc++11-extensions]
  std::string transform(std::string str) const override;
                                               ^
8 warnings and 12 errors generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
CMakeFiles/hext.dir/build.make:63: recipe for target 'CMakeFiles/hext.dir/src/AppendPipe.cpp.o' failed
make[4]: *** [CMakeFiles/hext.dir/src/AppendPipe.cpp.o] Error 1
make[4]: Leaving directory '/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hext.dir/all' failed
make[3]: *** [CMakeFiles/hext.dir/all] Error 2
make[3]: Leaving directory '/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/build'
Makefile:129: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/brando/src/hext-emscripten-tomastrapp/build/hext-0.8.0/libhext/build'
Makefile.libhext:18: recipe for target 'build-dep/lib/libhext.a' failed
make[1]: *** [build-dep/lib/libhext.a] Error 2
make[1]: Leaving directory '/home/brando/src/hext-emscripten-tomastrapp'
Makefile:15: recipe for target 'dependencies' failed
make: *** [dependencies] Error 2

```

Do I have the wrong version of clang or emscripten?

Emscripten version is 1.38.32
Clang version is 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

**Comment by thomastrapp** [comment]
Interesting. I'll try to reproduce this in a clean Ubuntu-18.04 docker image in the following days.

> Do I have the wrong version of clang or emscripten?

I noticed that your path to `em++` is `emsdk/emscripten/1.38.24/em++`. The path `emsdk/emscripten`  does not exist in my install of the SDK. When I build `hext-emscripten`, it uses `emsdk/fastcomp/emscripten/em++`.

I guess you are building the SDK from source.
I pull in the toolchain through the ["Python driver"](https://emscripten.org/docs/getting_started/downloads.html#installation-instructions).
Both methods should work, but my knowledge of emscripten is limited.

One thing you can try is doing a fresh reinstall of the `emsdk` using the "Python driver" or recompiling the latest source of emscripten (although 1.38.32 should be recent enough).

Details:
* The error messages show that the compiler does not accept C++17
* And indeed, CMake is not setting the C++ version (`--std=c++17`) when calling `em++`.
* But, libhext v0.8.0 requires this flag in: [`target_compile_features(hext PUBLIC cxx_std_17)`](https://github.com/html-extract/hext/blob/v0.8.0/libhext/CMakeLists.txt#L76)
* According to the CMake v3.10 documentation [`target_compile_features`](https://cmake.org/cmake/help/v3.10/command/target_compile_features.html) should either set the flag, or, if the compiler does not support it, report an error, which should abort the build. Puzzling.

**Comment by thomastrapp** [comment]
I was able to build `hext-emscripten` on a clean Ubuntu-18.04 image.

Dependencies:
```
apt-get install \
  wget git libdigest-sha-perl python2.7 python build-essential libxml2 \
  libtool autoconf rapidjson-dev cmake
```

And then:
```
# setup emsdk
cd ~
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
git pull
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh

# setup hext-emscripten
cd ~
git clone https://github.com/thomastrapp/hext-emscripten.git
cd hext-emscripten
make
make test
ls -lah hext-emscripten.*
```

Can you try this method?

Off topic: Turning this into a script that works on Travis CI should be straight forward. Travis could then build `hext-emscripten` automatically and upload the compiled files to the Github releases.

**Comment by brandonrobertz** [comment]
Okay so I've got it compiling (HINT: I *think* it was my system dependencies). I think I simply had the "clang" package installed. When I copied your apt-get install string, I was missing `rapidjson-dev`.

I also noticed this pop up:

```
The following package was automatically installed and is no longer required:
  libllvm7
```

After which, my compilation succeeded. The weird part is that removing the `libllvm7` library didn't change anything, but everything worked after that `rapidjson-dev` installation.

Anyway, we should add that to the deps so that it's explicit. Otherwise, this looks good and I'll merge it in. I'm also going to transfer the repo over.

**Comment by thomastrapp** [comment]
Yeah, there are probably a lot of ways the build can break. I am still amazed that it works at all, compiling to JavaScript that is.

Thanks for the merge and transfer!

**Pull request merged**
